apiVersion: v2
name: n8n
description: A Helm chart for n8n workflow automation
type: application
version: 1.0.0
appVersion: "latest"
keywords:
  - n8n
  - workflow
  - automation
home: https://n8n.io
sources:
  - https://github.com/n8n-io/n8n
maintainers:
  - name: doome972545
    email: domedoome9725451@gmail.com
