service:
  type: NodePort
  port: 5678
  nodePort: 30678

env:
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - name: N8N_BASIC_AUTH_USER
    value: "admin"
  - name: N8N_BASIC_AUTH_PASSWORD
    value: "admin"
  - name: WEBHOOK_URL
    value: "http://127.0.0.1:30678/"
  - name: N8N_SECURE_COOKIE
    value: "false"
